//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.ObjectModel;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.bookCat = new ObservableCollection<bookCat>();
            this.bookSubCat = new ObservableCollection<bookSubCat>();
            this.OrderDetail = new ObservableCollection<OrderDetail>();
            this.Recommend = new ObservableCollection<Recommend>();
            this.TimeBased = new ObservableCollection<TimeBased>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int PubID { get; set; }
        public string Author { get; set; }
        public string Summary { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }

        [JsonIgnore]
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ObservableCollection<bookCat> bookCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ObservableCollection<bookSubCat> bookSubCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ObservableCollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ObservableCollection<Recommend> Recommend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ObservableCollection<TimeBased> TimeBased { get; set; }
    }
}
